[tool.poetry]
name = "babbel-etl"
version = "0.1.0"
description = ""
authors = ["waqasar.mehmood <waqasar.mehmood@codapayments.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
